'use strict';

var WASP_IDENTIFIER = '__WASP__';

module.exports = {
  WASP_IDENTIFIER: WASP_IDENTIFIER,
  WASP_REQUEST_DATA: WASP_IDENTIFIER + 'REQUEST_GRAPHQL_DATA',
  WASP_RECEIVE_DATA: WASP_IDENTIFIER + 'RECEIVE_GRAPHQL_DATA',
  WASP_RECEIVE_ERROR: WASP_IDENTIFIER + 'RECEIVE_GRAPHQL_ERROR',
  WASP_CLEAR_DATA: WASP_IDENTIFIER + 'CLEAR_GRAPHQL_DATA'
};
