'use strict';

var WASP_IDENTIFIER = '__WASP__';

module.exports = {
  // Action Types
  WASP_IDENTIFIER: WASP_IDENTIFIER,
  REQUEST_GRAPHQL_DATA: 'REQUEST_GRAPHQL_DATA',
  RECEIVE_GRAPHQL_DATA: 'RECEIVE_GRAPHQL_DATA',
  RECEIVE_GRAPHQL_ERROR: 'RECEIVE_GRAPHQL_ERROR',
  CLEAR_GRAPHQL_DATA: 'CLEAR_GRAPHQL_DATA'
};
